[build]
  command = "yarn build"
  publish = "build"

[[redirects]]
  from = "https://upload.cecilianarchives.com/*"
  to = "https://www.cecilianarchives.com/upload/:splat"
  status = 301
  force = true

# Redirect default Netlify subdomain to primary domain
[[redirects]]
  from = "https://cecilian-archives.netlify.app/*"
  to = "https://www.cecilianarchives.com/:splat"
  status = 301
  force = true

# Send all other requests to index.html to allow client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
